services:

  # ==========================================
  # BACKEND
  # ==========================================

  backend:
    image: shreyanshp0/intervix-backend:latest

    container_name: intervix_backend

    pull_policy: always

    restart: unless-stopped

    ports:
      - "5000:5000"

    env_file:
      - ./Backend/.env

    environment:
      - NODE_ENV=production

      - DOCKER_CONTAINER=true

      - FRONTEND_URL=https://intervix.duckdns.org

      - PUBLIC_APP_URL=https://intervix.duckdns.org

      - TRUSTED_ORIGINS=https://intervix.duckdns.org,http://intervix.duckdns.org,http://localhost:3000

    mem_limit: 500m

    cpus: 0.75

    networks:
      - intervix-network

  # ==========================================
  # FRONTEND
  # ==========================================

  frontend:
    image: shreyanshp0/intervix-frontend:latest

    container_name: intervix_frontend

    pull_policy: always

    restart: unless-stopped

    ports:
      - "3000:80"

    env_file:
      - ./Frontend/.env

    environment:
      - NODE_ENV=production

      - DOCKER_CONTAINER=true

      - VITE_API_URL=/api

    depends_on:
      - backend

    mem_limit: 250m

    cpus: 0.50

    networks:
      - intervix-network

# ==========================================
# NETWORKS
# ==========================================

networks:
  intervix-network:
    driver: bridge